# Generated by Django 3.2.5 on 2021-08-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0002_alter_newurl_url_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newurl',
            name='id',
        ),
        migrations.AlterField(
            model_name='newurl',
            name='url_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
